# app/config/security.yml
security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~

    access_control:
          # require authentication
          - { path: ^/event/new, roles: ROLE_USER }
          - { path: ^/event/[0-9]+/edit$, roles: ROLE_USER }