# app/config/security.yml
security:

    encoders:
           Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EVENT_CREATE, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      in_memory:
          memory:
              users:
                  marko: { password: apelsin, roles: [ 'ROLE_USER' ] }
                  admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }


    firewalls:
        secured_area:
          pattern:    ^/
          form_login:
               login_path: login_form
               check_path: login_check
          logout:
              path:   logout
              target: event_index
          anonymous: ~
          switch_user: ~

    access_control:
          # require authentication
          - { path: ^/event/new, roles: ROLE_USER }
          - { path: ^/event/[0-9]+/edit$, roles: ROLE_USER }
          - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }