<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $username
     * @param $email
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneByUsernameOrEmail($username, $email) {
        return $this->createQueryBuilder('u')
               ->andWhere('u.username = :username OR u.email = :email')
               ->setParameter('username', $username)
               ->setParameter('email', $email)
               ->getQuery()
               ->getOneOrNullResult();
    }
}
